[config]
exclude-merge-commits=true
check-summary-length=true

[matchers]
simple="(?:feat|test|ref|fix|style|doc)\\(.*?\\) : .+(?:\n)?"
extended="(?:feat|test|ref|fix|style|doc)\\(.*?\\) : .+?\n(?:\n?.+)+(?:\n)?"

[examples]
a_simple_commit="""
[feat|test|ref|fix|style|doc](module) : A commit message
"""
an_extended_commit="""
[feat|test|ref|fix|style|doc](module) : A commit message

* first line
* second line
* and so on...
"""
